-- Transação 1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
SELECT * FROM FUNCIONARIO;
PRINT 'SELECT CONCLUIDO EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);
-- Pausa de 20 segundos
WAITFOR DELAY '00:00:20';
COMMIT TRAN;
PRINT 'TRANSAÇÃO 1 CONCLUIDA EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);

-- Transação 2
BEGIN TRAN;
INSERT INTO FUNCIONARIO (pnome, Minicial, Unome, cpf)
VALUES ('Matheus', 'M', 'Pichler', '04383221009');
PRINT 'INSERT CONCLUIDO EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);
COMMIT TRAN;
PRINT 'COMMIT EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);