-- TRANSACTION
-- ROLLBACK
-- COMMIT
-- SAVE POINT

BEGIN TRAN;

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('MARKETING DIGITAL', 88);

SAVE TRAN dptOK;

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('MARKETING DIGITAL', 99);

ROLLBACK TRAN dptOK;

COMMIT TRAN;

select * from DEPARTAMENTO