BEGIN TRY
    SELECT 1/0; -- ERRO
    PRINT 'não cheguei aqui';
END TRY
BEGIN CATCH
    PRINT 'DEU ERRO';
    PRINT 'NUMERO: ' + CAST(ERROR_NUMBER() AS VARCHAR(10));
    PRINT 'MENSAGEM: ' + ERROR_MESSAGE();
END CATCH